mysql-data:
  image: alpine
  command: echo "done."
  volumes:
    - /var/lib/mysql

mysql:
  build: ./mysql
  environment:
    MYSQL_ROOT_PASSWORD: secret
  volumes_from:
    - mysql-data
  expose:
    - "3306"

php:
  build: ./php
  links:
    - mysql:mysql
  expose:
    - "9000"
  volumes:
    - /your_project_local_path:/var/www/webroot

nginx:
  build: ./nginx
  links:
    - php:php
  volumes:
    - /your_project_local_path:/var/www/webroot
    - /your_log_local_path:/var/log
#    - /etc/letsencrypt:/etc/letsencrypt
  ports:
    - "80:80"
